dont run CRAN oldest
 - causing drone issues that dont really matter given the upcoming transition to github actions

Would error for `oldest` with the following message:
Error: (converted from warning) unable to access index for repository https://packagemanager.rstudio.com/all/__linux__/bionic/292/src/contrib:
  cannot open URL