feat: print.bbi_nonmem_summary: account for ONLYSIM
`bbi nonmem summary` used to fail with an out-of-bounds error when fed
ONLYSIM output, but it now sets the "only_sim" field.  With the bbi
failure removed, bbi_nonmem_summary() itself now fails for ONLYSIM
models.  For example, here's the model from bbi issue 224:

    > m %>% model_summary()
    Dataset: ../1001.csv

    Records: 2645	 Observations: 2620	 Subjects: 20

    Objective Function Value (final est. method): NA

    Estimation Method(s):

    –

    No Heuristic Problems Detected

    Error: All columns in a tibble must be vectors.
    ✖ Column `parameter_names` is NULL.
    ✖ Column `estimate` is NULL.
    ✖ Column `fixed` is NULL.

Teach bbi_nonmem_summary() to look for the only_sim flag and avoid
trying to do estimation-related processing that would lead to failures
for ONLYSIM.

Re: https://github.com/metrumresearchgroup/bbi/pull/258